### ISSUE TITLE
Assert in the protected package encoder with unknown implications for release build

### ISSUE THREAD

**Issue by nbars** [ngtcp2/ngtcp2#1193]
Hey,

I found an `assert` in the protected package encoder that can be triggered via remote. You may use [pernos.co](https://pernos.co/debug/UQwf7yVOVKnIHhOuak-lUA/index.html#f{m[Az4,AA_,t[Ag,NdJ5_,f{e[AzA,AQI_,s{aVVVVVUAA,bBQ,uDHOW,oDIBZ___/) to spawn an interactive `rr` session to debug the crash. Please reach out if you need any further assistance.

Best,
Nils

```
==223469==ERROR: AddressSanitizer: ABRT on unknown address 0x2424ee16000368ed (pc 0x7ffff643352b bp 0x000000000006 sp 0x7ffffffec620 T0)
    #0 0x7ffff643352b in __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
    #1 0x7ffff643352b in __pthread_kill_internal ./nptl/pthread_kill.c:78:10
    #2 0x7ffff643352b in pthread_kill ./nptl/pthread_kill.c:89:10
    #3 0x7ffff63de3b5 in raise ./signal/../sysdeps/posix/raise.c:26:13
    #4 0x7ffff63c487b in abort ./stdlib/abort.c:79:7
    #5 0x7ffff63c479a in __assert_fail_base ./assert/assert.c:92:3
    #6 0x7ffff63d5b65 in __assert_fail ./assert/assert.c:101:3
    #7 0x7ffff7d5a030 in ngtcp2_ppe_padding_hp_sample ngtcp2/consumer/lib/ngtcp2_ppe.c:191:3
    #8 0x7ffff7c4141f in ngtcp2_conn_write_single_frame_pkt ngtcp2/consumer/lib/ngtcp2_conn.c:4366:27
    #9 0x7ffff7cb8590 in conn_write_connection_close ngtcp2/consumer/lib/ngtcp2_conn.c:12164:16
    #10 0x7ffff7cb7957 in ngtcp2_conn_write_connection_close_pkt ngtcp2/consumer/lib/ngtcp2_conn.c:12251:12
    #11 0x7ffff7cbd07d in ngtcp2_conn_write_connection_close_versioned ngtcp2/consumer/lib/ngtcp2_conn.c:12419:12
    #12 0x55555574bd17 in Handler::start_closing_period() ngtcp2/consumer/examples/server.cc:2009:12
    #13 0x555555741c33 in Handler::handle_error() ngtcp2/consumer/examples/server.cc:2032:7
    #14 0x555555741c33 in Handler::write_streams() ngtcp2/consumer/examples/server.cc:1783:14
    #15 0x55555573aa96 in Handler::on_write() ngtcp2/consumer/examples/server.cc:1693:17
    #16 0x55555575d1f8 in Server::read_pkt(Endpoint&, ngtcp2::Address const&, sockaddr const*, unsigned int, ngtcp2_pkt_info const*, unsigned char const*, unsigned long) ngtcp2/consumer/examples/server.cc:2632:12
    #17 0x555555758bb7 in Server::on_read(Endpoint&) ngtcp2/consumer/examples/server.cc:2504:9
    #18 0x7ffff6ac0772 in ev_invoke_pending ??:0:0
    #19 0x7ffff6ac4040 in ev_run ??:0:0
    #20 0x555555772131 in main ngtcp2/consumer/examples/server.cc:3887:3
    #21 0x7ffff63c5a8f in __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #22 0x7ffff63c5b48 in __libc_start_main ./csu/../csu/libc-start.c:360:3
    #23 0x5555555938a4 in _start ??:0:0

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: ABRT (/lib/x86_64-linux-gnu/libc.so.6+0x9152b) (BuildId: d320ce4e63925d698610ed423fc4b1f0e8ed51f1)
```

**Comment by tatsuhiro-t** [comment]
It looks like AES 128 CCM is negotiated but the cipher retrieved from wolfssl session is AES 128 CTR, which is not AEAD and the cipher that QUIC supports.  I think this is wolfssl bug that it returns AES 128 CTR when AES 128 CCM is negotiated.

**Comment by icing** [comment]
wolfSSL has a PR (https://github.com/wolfSSL/wolfssl/pull/7465) supposedly fixing this.
