### ISSUE TITLE
 Crash due to bad address in fr->data[i].base

### ISSUE THREAD

**Issue by cute** [ngtcp2/ngtcp2#1215]
Hi. 

I encountered the following error:  (code=1, address=0x16b4fe78a). 
I found fr->data[i].base memory  address is 0x16b4fe78a and i is 0.

ngtcp2 version: 1.4.0.

https://github.com/ngtcp2/ngtcp2/blob/d375a5820af3be73711e71b0484cf3f5fbdb7ca0/lib/ngtcp2_pkt.c#L1580

Related code:
```
ngtcp2_ssize nwrite;
uint8_t buf[2000];
ssize_t ndatalen = 0;
uint32_t flags = NGTCP2_WRITE_STREAM_FLAG_NONE;
int64_t stream_id = -1;
nwrite = ngtcp2_conn_writev_stream(conn, NULL, NULL, buf, sizeof(buf),
                                   &ndatalen, flags, stream_id, NULL, 0, timestamp());
 ```
 
Crash report:

```

#0  0x00000001e6e72c1c in _platform_memmove ()
#1  0x000000010519dcd4 in ngtcp2_cpymem at ./ngtcp2/src/ngtcp2_str.c:32
#2  0x000000010518e578 in ngtcp2_pkt_encode_stream_frame at ./ngtcp2/src/ngtcp2_pkt.c:1580
#3  0x000000010518dfe4 in ngtcp2_pkt_encode_frame at ./ngtcp2/src/ngtcp2_pkt.c:1473
#4  0x0000000105191dc0 in ngtcp2_ppe_encode_frame at ./ngtcp2/src/ngtcp2_ppe.c:92
#5  0x0000000105171460 in conn_ppe_write_frame_hd_log at ./ngtcp2/src/ngtcp2_conn.c:1799
#6  0x00000001051693b4 in conn_write_pkt at ./ngtcp2/src/ngtcp2_conn.c:3768
#7  0x0000000105165e28 in ngtcp2_conn_write_vmsg at ./ngtcp2/src/ngtcp2_conn.c:12090
#8  0x0000000105164bec in conn_write_vmsg_wrapper at ./ngtcp2/src/ngtcp2_conn.c:11678
#9  0x000000010515ebc4 in ngtcp2_conn_writev_stream_versioned at ./ngtcp2/src/ngtcp2_conn.c:11744
```

**Comment by tatsuhiro-t** [comment]
This is retransmission of STREAM frame, Make sure you keep data passed to ngtcp2_conn_writev_stream alive until ngtcp2_acked_stream_data_offset that completely covers the data is called.

**Comment by cute** [comment]
Thank you very much for your response. I think I have identified the issue.
