### ISSUE TITLE
ASAN stack-buffer-overflow issue in ngtcp2?

### ISSUE THREAD

**Issue by roticv** [ngtcp2/ngtcp2#433]
I am working on https://github.com/roticv/simplerush which is based on ngtcp2 and I ran into some memory corruptions and started testing with ASAN. I ran into an ASAN abort where the internals of ngtcp2 is trying to access an invalid address in stack (which looks like wrong offset computation in ngtcp2). I don't know the internals of ngtcp2 well enough to diagnose what's the exact issue, but I can help diagnose further if I have some pointers.

```
==10005==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x70000e6ec555 at pc 0x00010e7aa02c bp 0x70000e6eb0b0 sp 0x70000e6ea870
WRITE of size 4 at 0x70000e6ec555 thread T1
    #0 0x10e7aa02b in wrap_memcpy+0x2ab (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x1d02b)
    #1 0x10df0fea1 in ngtcp2_cpymem+0x11 (libngtcp2.2.dylib:x86_64+0x5ea1)
    #2 0x10df0fc21 in ngtcp2_put_varint+0x61 (libngtcp2.2.dylib:x86_64+0x5c21)
    #3 0x10df0e4d6 in ngtcp2_pkt_encode_stream_frame+0x116 (libngtcp2.2.dylib:x86_64+0x44d6)
    #4 0x10df27e1a in ngtcp2_ppe_encode_frame+0x2a (libngtcp2.2.dylib:x86_64+0x1de1a)
    #5 0x10df1d961 in conn_ppe_write_frame_hd_log+0x21 (libngtcp2.2.dylib:x86_64+0x13961)
    #6 0x10df19a50 in conn_write_pkt+0x1200 (libngtcp2.2.dylib:x86_64+0xfa50)
    #7 0x10df175b6 in ngtcp2_conn_write_vmsg+0x926 (libngtcp2.2.dylib:x86_64+0xd5b6)
    #8 0x10df133a0 in ngtcp2_conn_writev_stream_versioned+0x100 (libngtcp2.2.dylib:x86_64+0x93a0)
    #9 0x10dc79810 in rush::QuicConnection::tryWriteStream()+0x5e0 (flv_to_rush_stream:x86_64+0x100022810)
    #10 0x10dc790b8 in rush::QuicConnection::tryWriteToNgtcp2()+0x18 (flv_to_rush_stream:x86_64+0x1000220b8)
    #11 0x10dc7834d in rush::(anonymous namespace)::read_cb(ev_loop*, ev_io*, int)+0x7d (flv_to_rush_stream:x86_64+0x10002134d)
    #12 0x10de2f5ed in ev_invoke_pending+0x59 (libev.4.dylib:x86_64+0x35ed)
    #13 0x10de2fab6 in ev_run+0x4ac (libev.4.dylib:x86_64+0x3ab6)
    #14 0x10dc65975 in rush::EvLoop::runLoop(int)+0xe5 (flv_to_rush_stream:x86_64+0x10000e975)
    #15 0x10dc84a45 in rush::RushClient::RushClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int)::$_0::operator()() const+0x55 (flv_to_rush_stream:x86_64+0x10002da45)
    #16 0x10dc849b4 in decltype(static_cast<rush::RushClient::RushClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int)::$_0>(fp)()) std::__1::__invoke<rush::RushClient::RushClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int)::$_0>(rush::RushClient::RushClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int)::$_0&&)+0x14 (flv_to_rush_stream:x86_64+0x10002d9b4)
    #17 0x10dc84954 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, rush::RushClient::RushClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, rush::RushClient::RushClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int)::$_0>&, std::__1::__tuple_indices<>)+0x24 (flv_to_rush_stream:x86_64+0x10002d954)
    #18 0x10dc83a2f in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, rush::RushClient::RushClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int)::$_0> >(void*)+0x11f (flv_to_rush_stream:x86_64+0x10002ca2f)
    #19 0x7ff801bee4f3 in _pthread_start+0x7c (libsystem_pthread.dylib:x86_64+0x64f3)
    #20 0x7ff801bea00e in thread_start+0xe (libsystem_pthread.dylib:x86_64+0x200e)

Address 0x70000e6ec555 is located in stack of thread T1 at offset 53 in frame
    #0 0x10dc7923f in rush::QuicConnection::tryWriteStream()+0xf (flv_to_rush_stream:x86_64+0x10002223f)

  This frame has 7 object(s):
    [32, 40) 'pi'
    [64, 12864) 'buf' <== Memory access at offset 53 underflows this variable
    [13120, 13416) 'ps'
    [13488, 13744) 'datav'
    [13808, 13816) 'streamId'
    [13840, 13848) 'wdatalen'
    [13872, 13876) 'fin'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T1 created by T0 here:
    #0 0x10e7cf67c in wrap_pthread_create+0x5c (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x4267c)
    #1 0x10dc83908 in std::__1::__libcpp_thread_create(_opaque_pthread_t**, void* (*)(void*), void*)+0x28 (flv_to_rush_stream:x86_64+0x10002c908)
    #2 0x10dc8349c in std::__1::thread::thread<rush::RushClient::RushClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int)::$_0, void>(rush::RushClient::RushClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int)::$_0&&)+0x22c (flv_to_rush_stream:x86_64+0x10002c49c)
    #3 0x10dc8322c in std::__1::thread::thread<rush::RushClient::RushClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int)::$_0, void>(rush::RushClient::RushClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int)::$_0&&)+0x1c (flv_to_rush_stream:x86_64+0x10002c22c)
    #4 0x10dc7c608 in std::__1::__unique_if<std::__1::thread>::__unique_single std::__1::make_unique<std::__1::thread, rush::RushClient::RushClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int)::$_0>(rush::RushClient::RushClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int)::$_0&&)+0x48 (flv_to_rush_stream:x86_64+0x100025608)
    #5 0x10dc7c04e in rush::RushClient::RushClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int)+0x2ce (flv_to_rush_stream:x86_64+0x10002504e)
    #6 0x10dc7cdc8 in rush::RushClient::RushClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int)+0x28 (flv_to_rush_stream:x86_64+0x100025dc8)
    #7 0x10dc5e061 in main+0x341 (flv_to_rush_stream:x86_64+0x100007061)
    #8 0x10faca4fd in start+0x1cd (dyld:x86_64+0x54fd)

SUMMARY: AddressSanitizer: stack-buffer-overflow (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x1d02b) in wrap_memcpy+0x2ab
Shadow bytes around the buggy address:
  0x1e0001cdd850: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e0001cdd860: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e0001cdd870: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e0001cdd880: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e0001cdd890: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x1e0001cdd8a0: 00 00 00 00 f1 f1 f1 f1 00 f2[f2]f2 00 00 00 00
  0x1e0001cdd8b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e0001cdd8c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e0001cdd8d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e0001cdd8e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1e0001cdd8f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==10005==ABORTING
```

**Comment by tatsuhiro-t** [comment]
Do you keep unacknowledged data until [ngtcp2_acked_stream_data_offset](https://nghttp2.org/ngtcp2/types.html#c.ngtcp2_acked_stream_data_offset) is called?

**Comment by roticv** [comment]
In the version of code that caused the above ASAN, I commented out the code that removed any data (to reduce any other possibilities). So the unacknowledged data is never removed/freed.

**Comment by tatsuhiro-t** [comment]
It seems to me that your program does not complete quic packet in a certain condition.
If NGTCP2_WRITE_STREAM_FLAG_MORE is used, a caller must keep calling ngtcp2_conn_writev_stream makes a complete quic packet or 0 or negative error (some exception here, see the doc below).
https://nghttp2.org/ngtcp2/ngtcp2_conn_writev_stream.html

**Comment by tatsuhiro-t** [comment]
So, when NGTCP2_WRITE_STREAM_FLAG_MORE is used, ngtcp2_conn keeps the given buffer address in its state until ngtcp2_conn_writev_stream creates a complete QUIC packet or returns fatal error.  The given buffer is stack allocated, and if the stack is cleared before the function does not produce the packet, in the next ngtcp2_conn_writev_stream might be called in the different call stack, which may change buffer offset that creates ASAN failure.

**Comment by roticv** [comment]
Thanks! I removed that option and tested for a while and the ASAN stack-buffer-overflow is gone.

Thank you so much!
